swagger: '2.0'
info:
  title: Initia - REST docs
  description: A REST interface for state queries
  version: 1.0.0
paths:
  /initia/ibchooks/v1/acls:
    get:
      summary: ACLs gets ACL entries.
      operationId: ACLs
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              acls:
                type: array
                items:
                  type: object
                  properties:
                    address:
                      type: string
                    allowed:
                      type: boolean
                  description: ACL defines the ACL entry of an address.
              pagination:
                description: pagination defines the pagination in the response.
                type: object
                properties:
                  next_key:
                    type: string
                    format: byte
                    description: |-
                      next_key is the key to be passed to PageRequest.key to
                      query the next page most efficiently. It will be empty if
                      there are no more results.
                  total:
                    type: string
                    format: uint64
                    title: >-
                      total is total number of results available if
                      PageRequest.count_total

                      was set, its value is undefined otherwise
            title: |-
              QueryACLsResponse is the response type for the
              Query/ACLAddrs RPC method
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: pagination.key
          description: |-
            key is a value returned in PageResponse.next_key to begin
            querying the next page most efficiently. Only one of offset or key
            should be set.
          in: query
          required: false
          type: string
          format: byte
        - name: pagination.offset
          description: >-
            offset is a numeric offset that can be used when key is unavailable.

            It is less efficient than using key. Only one of offset or key
            should

            be set.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.limit
          description: >-
            limit is the total number of results to be returned in the result
            page.

            If left empty it will default to a value to be set by each app.
          in: query
          required: false
          type: string
          format: uint64
        - name: pagination.count_total
          description: >-
            count_total is set to true  to indicate that the result set should
            include

            a count of the total number of items available for pagination in
            UIs.

            count_total is only respected when offset is used. It is ignored
            when key

            is set.
          in: query
          required: false
          type: boolean
        - name: pagination.reverse
          description: >-
            reverse is set to true if results are to be returned in the
            descending order.


            Since: cosmos-sdk 0.43
          in: query
          required: false
          type: boolean
      tags:
        - Query
  /initia/ibchooks/v1/acls/{address}:
    get:
      summary: ACL gets ACL entry of an address.
      operationId: ACL
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              acl:
                type: object
                properties:
                  address:
                    type: string
                  allowed:
                    type: boolean
                description: ACL defines the ACL entry of an address.
            title: |-
              QueryACLResponse is the response type for the Query/ACL RPC
              method
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: address
          description: >-
            Address is a contract address (wasm, evm) or a contract deployer
            address (move).
          in: path
          required: true
          type: string
      tags:
        - Query
  /initia/ibchooks/v1/params:
    get:
      summary: Params queries all parameters.
      operationId: IBCHooksParams
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              params:
                description: params defines the parameters of the module.
                type: object
                properties:
                  default_allowed:
                    type: boolean
                    description: |-
                      if the ACL of a address is not set,
                      then we use this value to decide the ACL.
            description: >-
              QueryParamsResponse is the response type for the Query/Params RPC
              method.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      tags:
        - Query
  /initia/abcipp/mempool/v1/distribution:
    get:
      summary: >-
        QueryTxDistribution returns the distribution of transactions in the
        mempool.
      operationId: QueryTxDistribution
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              distribution:
                type: object
                additionalProperties:
                  type: string
                  format: uint64
                description: >-
                  Distribution is a map of lane to the number of transactions in
                  the mempool for that lane.
            description: >-
              QueryTxDistributionResponse is the response type for the
              Query.QueryTxDistribution

              RPC method.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      tags:
        - Query
  /initia/abcipp/mempool/v1/{sender}/{sequence}:
    get:
      summary: QueryTxHash checks if a transaction is in the mempool.
      operationId: QueryTxHash
      responses:
        '200':
          description: A successful response.
          schema:
            type: object
            properties:
              txHash:
                type: string
            description: |-
              QueryTxHashResponse is the response type for the Query.QueryTxHash
              RPC method.
        default:
          description: An unexpected error response.
          schema:
            type: object
            properties:
              error:
                type: string
              code:
                type: integer
                format: int32
              message:
                type: string
              details:
                type: array
                items:
                  type: object
                  properties:
                    type_url:
                      type: string
                    value:
                      type: string
                      format: byte
      parameters:
        - name: sender
          in: path
          required: true
          type: string
        - name: sequence
          in: path
          required: true
          type: string
      tags:
        - Query
definitions:
  cosmos.base.query.v1beta1.PageRequest:
    type: object
    properties:
      key:
        type: string
        format: byte
        description: |-
          key is a value returned in PageResponse.next_key to begin
          querying the next page most efficiently. Only one of offset or key
          should be set.
      offset:
        type: string
        format: uint64
        description: |-
          offset is a numeric offset that can be used when key is unavailable.
          It is less efficient than using key. Only one of offset or key should
          be set.
      limit:
        type: string
        format: uint64
        description: >-
          limit is the total number of results to be returned in the result
          page.

          If left empty it will default to a value to be set by each app.
      count_total:
        type: boolean
        description: >-
          count_total is set to true  to indicate that the result set should
          include

          a count of the total number of items available for pagination in UIs.

          count_total is only respected when offset is used. It is ignored when
          key

          is set.
      reverse:
        type: boolean
        description: >-
          reverse is set to true if results are to be returned in the descending
          order.


          Since: cosmos-sdk 0.43
    description: |-
      message SomeRequest {
               Foo some_parameter = 1;
               PageRequest pagination = 2;
       }
    title: |-
      PageRequest is to be embedded in gRPC request messages for efficient
      pagination. Ex:
  cosmos.base.query.v1beta1.PageResponse:
    type: object
    properties:
      next_key:
        type: string
        format: byte
        description: |-
          next_key is the key to be passed to PageRequest.key to
          query the next page most efficiently. It will be empty if
          there are no more results.
      total:
        type: string
        format: uint64
        title: |-
          total is total number of results available if PageRequest.count_total
          was set, its value is undefined otherwise
    description: |-
      PageResponse is to be embedded in gRPC response messages where the
      corresponding request message has used PageRequest.

       message SomeResponse {
               repeated Bar results = 1;
               PageResponse page = 2;
       }
  google.protobuf.Any:
    type: object
    properties:
      type_url:
        type: string
      value:
        type: string
        format: byte
  grpc.gateway.runtime.Error:
    type: object
    properties:
      error:
        type: string
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            type_url:
              type: string
            value:
              type: string
              format: byte
  initia.ibchooks.v1.ACL:
    type: object
    properties:
      address:
        type: string
      allowed:
        type: boolean
    description: ACL defines the ACL entry of an address.
  initia.ibchooks.v1.Params:
    type: object
    properties:
      default_allowed:
        type: boolean
        description: |-
          if the ACL of a address is not set,
          then we use this value to decide the ACL.
    description: Params defines the set of hook parameters.
  initia.ibchooks.v1.QueryACLResponse:
    type: object
    properties:
      acl:
        type: object
        properties:
          address:
            type: string
          allowed:
            type: boolean
        description: ACL defines the ACL entry of an address.
    title: |-
      QueryACLResponse is the response type for the Query/ACL RPC
      method
  initia.ibchooks.v1.QueryACLsResponse:
    type: object
    properties:
      acls:
        type: array
        items:
          type: object
          properties:
            address:
              type: string
            allowed:
              type: boolean
          description: ACL defines the ACL entry of an address.
      pagination:
        description: pagination defines the pagination in the response.
        type: object
        properties:
          next_key:
            type: string
            format: byte
            description: |-
              next_key is the key to be passed to PageRequest.key to
              query the next page most efficiently. It will be empty if
              there are no more results.
          total:
            type: string
            format: uint64
            title: >-
              total is total number of results available if
              PageRequest.count_total

              was set, its value is undefined otherwise
    title: |-
      QueryACLsResponse is the response type for the
      Query/ACLAddrs RPC method
  initia.ibchooks.v1.QueryParamsResponse:
    type: object
    properties:
      params:
        description: params defines the parameters of the module.
        type: object
        properties:
          default_allowed:
            type: boolean
            description: |-
              if the ACL of a address is not set,
              then we use this value to decide the ACL.
    description: QueryParamsResponse is the response type for the Query/Params RPC method.
  initia.abcipp.mempool.v1.QueryTxDistributionResponse:
    type: object
    properties:
      distribution:
        type: object
        additionalProperties:
          type: string
          format: uint64
        description: >-
          Distribution is a map of lane to the number of transactions in the
          mempool for that lane.
    description: >-
      QueryTxDistributionResponse is the response type for the
      Query.QueryTxDistribution

      RPC method.
  initia.abcipp.mempool.v1.QueryTxHashResponse:
    type: object
    properties:
      txHash:
        type: string
    description: |-
      QueryTxHashResponse is the response type for the Query.QueryTxHash
      RPC method.
