name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*"
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: minievm

jobs:
  build-image:
    name: Build Docker image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true
          build-args: |
            VERSION=${{ github.ref_name }}
            COMMIT=${{ github.sha }}
